import assert from "node:assert/strict";
import test from "node:test";
import {
	INBOUND_ARCHIVE_RECONCILIATION_BATCH_SIZE,
	INBOUND_ACTIVE_RECONCILIATION_BATCH_SIZE,
	INBOUND_RECENT_RAW_MAX_PREFIX_LIST_CALLS,
	INBOUND_RECENT_RAW_RECONCILIATION_BATCH_SIZE,
	INBOUND_RAW_BACKSTOP_RECONCILIATION_BATCH_SIZE,
	INBOUND_CLEANUP_INTENT_RECONCILIATION_BATCH_SIZE,
	INBOUND_RECONCILIATION_SERVICE_SUBREQUEST_BUDGET,
	INBOUND_RECONCILIATION_WORST_CASE_SERVICE_SUBREQUESTS,
	INBOUND_REPAIR_ATTEMPT_RECONCILIATION_BATCH_SIZE,
	MAX_ACTIVE_ARCHIVE_SERVICE_SUBREQUESTS_PER_ITEM,
	MAX_ARCHIVE_SERVICE_SUBREQUESTS_PER_ITEM,
	MAX_RECENT_RAW_SERVICE_SUBREQUESTS_PER_ITEM,
	RECENT_RAW_LANE_OVERHEAD_SERVICE_SUBREQUESTS,
	RECONCILIATION_LANE_COUNT,
	MAX_CLEANUP_INTENT_SERVICE_SUBREQUESTS_PER_ITEM,
	MAX_CLEANUP_INTENT_DISCOVERY_LIST_CALLS,
	MAX_REPAIR_ATTEMPT_SERVICE_SUBREQUESTS_PER_ITEM,
	RECONCILIATION_LANE_OVERHEAD_SERVICE_SUBREQUESTS,
	WORKER_DEFAULT_SERVICE_SUBREQUEST_LIMIT,
} from "./inbound-reconciliation-budget.ts";

test("the scheduled reconciliation shape stays below its structural service-subrequest budget", () => {
	assert.equal(INBOUND_REPAIR_ATTEMPT_RECONCILIATION_BATCH_SIZE, 20);
	assert.equal(MAX_REPAIR_ATTEMPT_SERVICE_SUBREQUESTS_PER_ITEM, 7);
	assert.equal(INBOUND_CLEANUP_INTENT_RECONCILIATION_BATCH_SIZE, 7);
	assert.equal(MAX_CLEANUP_INTENT_DISCOVERY_LIST_CALLS, 514);
	assert.equal(MAX_CLEANUP_INTENT_SERVICE_SUBREQUESTS_PER_ITEM, 520);
	assert.equal(INBOUND_ARCHIVE_RECONCILIATION_BATCH_SIZE, 9);
	assert.equal(INBOUND_ACTIVE_RECONCILIATION_BATCH_SIZE, 8);
	assert.equal(INBOUND_RAW_BACKSTOP_RECONCILIATION_BATCH_SIZE, 1);
	assert.equal(INBOUND_RECENT_RAW_RECONCILIATION_BATCH_SIZE, 128);
	assert.equal(INBOUND_RECENT_RAW_MAX_PREFIX_LIST_CALLS, 64);
	assert.equal(MAX_RECENT_RAW_SERVICE_SUBREQUESTS_PER_ITEM, 2);
	assert.equal(RECENT_RAW_LANE_OVERHEAD_SERVICE_SUBREQUESTS, 68);
	assert.equal(MAX_ARCHIVE_SERVICE_SUBREQUESTS_PER_ITEM, 521);
	assert.equal(MAX_ACTIVE_ARCHIVE_SERVICE_SUBREQUESTS_PER_ITEM, 523);
	assert.equal(RECONCILIATION_LANE_OVERHEAD_SERVICE_SUBREQUESTS, 3);
	assert.equal(RECONCILIATION_LANE_COUNT, 4);
	assert.equal(INBOUND_RECONCILIATION_WORST_CASE_SERVICE_SUBREQUESTS, 8_821);
	assert.ok(
		INBOUND_RECONCILIATION_WORST_CASE_SERVICE_SUBREQUESTS <=
			INBOUND_RECONCILIATION_SERVICE_SUBREQUEST_BUDGET,
	);
	assert.equal(INBOUND_RECONCILIATION_SERVICE_SUBREQUEST_BUDGET, 9_000);
	assert.equal(WORKER_DEFAULT_SERVICE_SUBREQUEST_LIMIT, 10_000);
	assert.ok(
		INBOUND_RECONCILIATION_SERVICE_SUBREQUEST_BUDGET <
			WORKER_DEFAULT_SERVICE_SUBREQUEST_LIMIT,
	);
});
